/* confdefs.h */
#define PACKAGE_NAME "bm"
#define PACKAGE_TARNAME "bm"
#define PACKAGE_VERSION "1.15.0-9631fc66"
#define PACKAGE_STRING "bm 1.15.0-9631fc66"
#define PACKAGE_BUGREPORT "antonin@barefootnetworks.com"
#define PACKAGE_URL ""
#define PACKAGE "bm"
#define VERSION "1.15.0-9631fc66"
#define DEBUG_ON /**/
#define LOG_DEBUG_ON /**/
#define LOG_TRACE_ON /**/
#define ELOG_ON /**/
#define WP4_16_STACKS /**/
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_CXX11 1
#define THRIFT_ON /**/
#define THRIFT_VERSION 1300
#define HAVE_PI_PI_H 1
#define HAVE_PI_TARGET_PI_IMP_H 1
#define HAVE_PI_P4INFO_H 1
#define HAVE_ALGORITHM 1
#define HAVE_ARRAY 1
#define HAVE_CASSERT 1
#define HAVE_CMATH 1
#define HAVE_QUEUE 1
#define HAVE_CSTDIO 1
#define HAVE_STRING 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_CTIME 1
#define HAVE_TUPLE 1
#define HAVE_UNISTD_H 1
#define HAVE_UNORDERED_MAP 1
#define HAVE_UTILITY 1
#define HAVE_VECTOR 1
#define HAVE_LIBNANOMSG 1
#define NANOMSG_ON /**/
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define HAVE_PTHREAD 1
#define HAVE_LIBGMP 1
#define HAVE_LIBPCAP 1
#define HAVE_DLFCN_H 1
#define HAVE_DLOPEN /**/
#define ENABLE_MODULES /**/
#define HAVE_LIBBOOST_THREAD 1
